= Update Meeting

== Input attributes

When you want to update your meetings component, you need to rely on the `MeetingAttributes` type, which has the following input fields:

[source]
----
• address               (Optional) - String
• available_slots       (Optional) - Integer
• description           (Required) - String
• end_time              (Required) - DateTime
• latitude              (Optional) - coordinate
• longitude             (Optional) - coordinate
• location_hints        (Optional) - String
• location              (Optional) - String
• online_meeting_url    (Optional) - String
• registration_terms    (Optional) - String
• registration_type     (Required) - RegistrationTypeType
• registration_url      (Optional) - String
• registrations_enabled (Optional) - Boolean
• start_time            (Required) - DateTime
• taxonomies            (Optional) - Taxonomy ids to assign to this meeting
• title                 (Required) - String
• type_of_meeting       (Required) - TypeOfMeeting
----

You may want to check the following input types:

* https://nightly.decidim.org/api/docs/enum/typeofmeetingenum/[TypeOfMeetingEnum]
* https://nightly.decidim.org/api/docs/enum/registrationtypeenum/[RegistrationTypeEnum]
* https://nightly.decidim.org/api/docs/enum/iframeembedtypeenum/[IframeEmbedTypeEnum]
* https://nightly.decidim.org/api/docs/enum/iframeaccesslevelenum/[IframeAccessLevelEnum]

== Sample request

The `UpdateMeeting` mutation allows authenticated users to update meetings in a Decidim meetings component. This mutation uses the existing `UpdateMeeting` command from the controller.

[source,graphql]
----
mutation updateMeeting($componentId: ID!, $meetingId: ID!, $input: UpdateMeetingInput!){
  component(id: $componentId) {
    ... on MeetingsMutation {
      meeting(id: $meetingId) {
        update(input: $input) {
          id
          title { translation(locale: "en") }
        }
      }
    }
  }
}
----

Example of submitted variables

[source,json]
----
{
  "componentId": 670,
  "meetingId": "2",
  "input": {
    "locale": "en",
    "attributes": {
      "address": "Carrer de la Pau, 1, Barcelona",
      "availableSlots": 10,
      "description": "Cities need more people, not more cars",
      "endTime": "2025-12-24T22:10:22Z",
      "iframeAccessLevel": "ALL",
      "iframeEmbedType": "NONE",
      "latitude": 40.1234,
      "location": "Somewhere",
      "locationHints": "Near the main square",
      "longitude": 2.1234,
      "onlineMeetingUrl": "https://meets.example.org/abc-def",
      "registrationTerms": "By registering you agree to the terms and conditions",
      "registrationType": "ON_THIS_PLATFORM",
      "registrationUrl": "https://example.org/register",
      "registrationsEnabled": true,
      "startTime": "2025-12-24T20:10:22Z",
      "taxonomies": [1072],
      "title": "More sidewalks and less roads",
      "typeOfMeeting": "ONLINE"
    }
  }
}
----

== Error Handling

The most frequent errors that can be generated by this mutation are as follows:

* xref:develop:api/reference/errors/unauthorized_mutation.adoc[Unauthorized Mutation Error - MUTATION_NOT_AUTHORIZED_ERROR]
* xref:develop:api/reference/errors/attribute_validation_error.adoc[Attribute Validation Error - ATTRIBUTE_VALIDATION_ERROR]
* xref:develop:api/reference/errors/unauthorized_object.adoc[Unauthorized Object Error - UNAUTHORIZED_OBJECT_ERROR]
