= Update Debate

== Input attributes

When you want to update data in your debates component, you need to rely on the `DebateAttributes` type, which has the following input fields:

[source]
----
• title                 (required) - String
• description           (required) - String
• taxonomies            (optional) - Taxonomy ids to assign to this debate
----

== Sample request

The `UpdateDebate` mutation allows authenticated users to update debates in a Decidim debates component. This mutation uses the existing `UpdateDebate` command from the controller.

[source,graphql]
----
mutation updateDebate($componentId: ID!,$debateId: ID!, $input: UpdateDebateInput!){
  component(id: $componentId) {
    ...on DebatesMutation{
      debate(id: $debateId){
        update(input: $input) {
          id
          title { translation(locale: "en") }
          description { translation(locale: "en") }
          taxonomies {
            name { translation(locale: "en") }
          }
        }
      }
    }
  }
}
----

Example of submitted variables

[source,json]
----
{
  "componentId": "5",
  "debateId": "9",
  "input": {
    "locale": "en",
    "attributes": {
      "description": "Cities need more people, not more cars",
      "taxonomies": [11],
      "title": "More sidewalks and less roads"
    }
  }
}
----

== Error Handling

The most frequent errors that can be generated by this mutation are as follows:

* xref:develop:api/reference/errors/unauthorized_mutation.adoc[Unauthorized Mutation Error - MUTATION_NOT_AUTHORIZED_ERROR]
* xref:develop:api/reference/errors/attribute_validation_error.adoc[Attribute Validation Error - ATTRIBUTE_VALIDATION_ERROR]
* xref:develop:api/reference/errors/unauthorized_object.adoc[Unauthorized Object Error - UNAUTHORIZED_OBJECT_ERROR]

