= ActiveStorage

Decidim uses https://edgeguides.rubyonrails.org/active_storage_overview.html[ActiveStorage] as the backend to store any user uploaded content. This allows Decidim implementers to easily plug Decidim to different kinds of storage APIs, such as Amazon S3, Google Cloud Storage or Azure Storage. By default, the user uploaded content will be stored to the same file disk where the Decidim application is running at. The default behavior may be problematic with some PaaS providers, such as Heroku.

In order to plug Decidim into a storage provider of your choice, you need to generate the Decidim application using the `--storage` modifier as explained at the xref:configure:index.adoc[configuration guide]. You will also need to provide the correct configuration options for the selected storage provider as explained at the xref:configure:environment_variables.adoc[environment variables guide].

[NOTE]
====
If you use any other provider than the default (`local`) you will need to also configure the xref:customize:content_security_policy.adoc[Content security policy]. For the directives "default-src", "img-src", "media-src", and "connect-src"`.
====

== Dynamic file uploads

Decidim allows participants to upload files dynamically from their browsers to the website using the upload modals where participants can drag and drop the files to or select them from their computer. With the default configuration using a local file storage, this feature does not require any additional configuration. With external storage providers, you have to configure those storages properly to support the client-side file uploads to Decidim.

In order to make the dynamic client-side uploads work with external storage providers, you also need to configure the CORS policies correctly. Example configurations for different storage providers are provided in the following sections which are based on the https://edgeguides.rubyonrails.org/active_storage_overview.html#cross-origin-resource-sharing-cors-configuration[official Rails documentation].

=== Amazon S3

Locate the bucket, go into the "Permissions" tab and find the section titled "CORS" from there. Edit the "CORS" settings and add the following configuration options to the editable field (replace `https://www.example.com` with the actual domain of your service):


[source,json]
----
[
  {
    "AllowedHeaders": [
      "*"
    ],
    "AllowedMethods": [
      "GET"
      "PUT"
    ],
    "AllowedOrigins": [
      "https://www.example.com"
    ],
    "ExposeHeaders": [
      "Origin",
      "Content-Type",
      "Content-MD5",
      "Content-Disposition"
    ],
    "MaxAgeSeconds": 3600
  }
]
----

Read more at https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors.html[Amazon S3 CORS documentation].

==== Public assets

To have public assets in your application, so that you do not rely on the ActiveStorage redirect system, you need to configure your bucket as follows:

1. Go to your AWS S3 console
2. Select the bucket you are using for uploads
3. Open the *Permissions* tab
4. In the *Block public access* section, click *Edit*
5. Disable all blocking options by *unchecking* every box:
  - "Block all public access"
  - "Block public access to buckets and objects granted through new access control lists (ACLs)"
  - "Block public access to buckets and objects granted through any access control lists (ACLs)"
  - "Block public access to buckets and objects granted through new public bucket or access point policies"
  - "Block public and cross-account access to buckets and objects through any public bucket or access point policies"
6. Click *Save changes*
7. Still in the *Permissions tab*, locate the *Bucket policy section* and click *Edit*.
8. Add a bucket policy similar to the example below.
   - If you are unsure of your bucket’s ARN, you can find it in the Properties tab. For this example, we use  `arn:aws:s3:::your-bucket-name`
9. Click *Save changes*
[source,json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Statement1",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::your-bucket-name/*"
        }
    ]
}
----

[NOTE]
====
If you use any other provider than the default (`local`) you will need to also configure the xref:customize:content_security_policy.adoc[Content security policy]. For the directives "img-src", "media-src", and "connect-src" adding some additional content like https://$YOUR-BUCKET-NAME.s3.$YOUR-AWS-REGION.amazonaws.com/*  (should look like: https://your-bucket-name.s3.eu-west-1.amazonaws.com)
====

===  Google Cloud Storage

Google Cloud Storage requires you to use the `gsutil` command line tool to set the CORS policy on your bucket. First you need to know the name of your bucket and then use the following command (replace `your-bucket-name` with the actual name of the bucket):

[source,bash]
----
gsutil cors set cors.json gs://your-bucket-name
----

Before running that command you need to have a `cors.json` file in the same directory where you are running the command from with the following content (replace `https://www.example.com` with the actual domain of your service):

[source,json]
----
[
  {
    "origin": ["https://www.example.com"],
    "method": ["GET", "PUT"],
    "responseHeader": ["Origin", "Content-Type", "Content-MD5", "Content-Disposition"],
    "maxAgeSeconds": 3600
  }
]
----

Read more at https://cloud.google.com/storage/docs/configuring-cors[Google Cloud Storage CORS documentation].

=== Azure Storage

Locate the storage account from the Azure Portal and go to the "Resource sharing (CORS)" section under "Settings. Fill in the following configuration options in the "Blob service" tab of that section (replace `https://www.example.com` with the actual domain of your service):

- **Allowed origins**: https://www.example.com
- **Allowed methods**: GET,PUT
- **Allowed headers**: *
- **Exposed headers**: Origin, Content-Type, Content-MD5, x-ms-blob-content-disposition, x-ms-blob-type
- **Max age**: 3600

When using the Azure REST API, you can use the `Set Blob Service Properties` operation with the following rule definitions to achieve the same (replace `https://www.example.com` with the actual domain of your service):

[source,xml]
----
<Cors>
  <CorsRule>
    <AllowedOrigins>https://www.example.com</AllowedOrigins>
    <AllowedMethods>GET,PUT</AllowedMethods>
    <AllowedHeaders>*</AllowedHeaders>
    <ExposedHeaders>Origin, Content-Type, Content-MD5, x-ms-blob-content-disposition, x-ms-blob-type</ExposedHeaders>
    <MaxAgeInSeconds>3600</MaxAgeInSeconds>
  </CorsRule>
</Cors>
----

Read more at https://docs.microsoft.com/en-us/rest/api/storageservices/cross-origin-resource-sharing--cors--support-for-the-azure-storage-services[Azure Storage CORS documentation].
