= Create Milestone

== Input attributes

When you want to add or create a milestones in your accountability component, you need to rely on the `MilestoneAttributes` type, which has the following input fields:

[source]
----
• title                             (Required)   - JSON
• entry_date                        (Required)   - String
• description                       (Optional)   - JSON
----

== Sample request

The `CreateMilestone` mutation allows authenticated administrators to create new milestones in a Decidim accountability component. This mutation uses the existing `CreateMilestone` command from the admin controller.

[source,graphql]
----
mutation createMilestone($componentId: ID!, $resultId: ID!, $input: CreateMilestoneInput!){
  component(id: $componentId) {
    ... on AccountabilityMutation {
      result(id: $resultId) {
        createMilestone(input: $input) {
          id
        }
      }
    }
  }
}
----

Example of submitted variables

[source,json]
----
{
  "componentId": "3",
  "resultId": "5",
  "input": {
    "attributes": {
      "title": { "en": "My milestone title" },
      "description": { "en": "A brief description of the milestone." },
      "entryDate": "2025-12-31"
    }
  }
}
----

== Error Handling

The most frequent errors that can be generated by this mutation are as follows:

* xref:develop:api/reference/errors/unauthorized_mutation.adoc[Unauthorized Mutation Error - MUTATION_NOT_AUTHORIZED_ERROR]
* xref:develop:api/reference/errors/invalid_locale_error.adoc[Invalid Locale Error - INVALID_LOCALE_ERROR]
* xref:develop:api/reference/errors/attribute_validation_error.adoc[Attribute Validation Error - ATTRIBUTE_VALIDATION_ERROR]
* xref:develop:api/reference/errors/unauthorized_object.adoc[Unauthorized Object Error - UNAUTHORIZED_OBJECT_ERROR]
