= Update Milestone

== Input attributes

When you want to update a milestone inside your accountability component, you need to rely on the `MilestoneAttributes` type, which has the following input fields:

[source]
----
• title                             (Optional)   - JSON
• entry_date                        (Optional)   - String
• description                       (Optional)   - JSON
----

== Sample request

The `UpdateMilestone` mutation allows authenticated administrators to update a milestone within a result in a Decidim accountability component. This mutation uses the existing `UpdateMilestone` command from the admin controller.

[source,graphql]
----
mutation updateMilestone($componentId: ID!, $resultId: ID!, $input: UpdateMilestoneInput!){
   component(id: $componentId){
    ... on AccountabilityMutation {
      result(id: $resultId){
      	updateMilestone(input: $input){
          id
        }
      }
    }
  }
}
----

Example of submitted variables

[source,json]
----
{
  "componentId": "3",
  "resultId": "5",
  "input": {
    "id": "7",
    "attributes": {
      "entryDate": "2025-12-31",
      "description": {
        "en": "Milestone description changed from API"
      },
      "title": {
        "en": "Milestone title changed from API"
      }
    }
  }
}
----

== Error Handling

The most frequent errors that can be generated by this mutation are as follows:

* xref:develop:api/reference/errors/unauthorized_mutation.adoc[Unauthorized Mutation Error - MUTATION_NOT_AUTHORIZED_ERROR]
* xref:develop:api/reference/errors/invalid_locale_error.adoc[Invalid Locale Error - INVALID_LOCALE_ERROR]
* xref:develop:api/reference/errors/attribute_validation_error.adoc[Attribute Validation Error - ATTRIBUTE_VALIDATION_ERROR]
* xref:develop:api/reference/errors/unauthorized_object.adoc[Unauthorized Object Error - UNAUTHORIZED_OBJECT_ERROR]
