= Create Budget

== Input attributes

When you want to add or create data in your budget component, you need to rely on the `BudgetAttributes` type, which has the following input fields:

[source]
----
• title                 (Optional) - JSON
• description           (Optional) - JSON
• total_budget          (Optional) - Integer
• weight                (Optional) - Integer
----

== Sample request

The `CreateBudget` mutation allows authenticated administrators to create new budgets in a Decidim budget component. This mutation uses the existing `CreateBudget` command from the admin controller.

[source,graphql]
----
mutation createBudget($componentId: ID!, $input: CreateBudgetInput!){
  component(id: $componentId) {
    ... on BudgetsMutation {
      createBudget(input: $input){
        id
        url
      }
    }
  }
}
----

Example of submitted variables

[source,json]
----
{
  "componentId": "3",
  "input": {
    "attributes": {
      "totalBudget": 1234,
      "title": {
        "en": "Budget created from API"
      }
    }
  }
}
----

== Error Handling

The most frequent errors that can be generated by this mutation are as follows:

* xref:develop:api/reference/errors/unauthorized_mutation.adoc[Unauthorized Mutation Error - MUTATION_NOT_AUTHORIZED_ERROR]
* xref:develop:api/reference/errors/invalid_locale_error.adoc[Invalid Locale Error - INVALID_LOCALE_ERROR]
* xref:develop:api/reference/errors/attribute_validation_error.adoc[Attribute Validation Error - ATTRIBUTE_VALIDATION_ERROR]
* xref:develop:api/reference/errors/unauthorized_object.adoc[Unauthorized Object Error - UNAUTHORIZED_OBJECT_ERROR]
