= Update Budget

== Input attributes

When you want to update data in your budget component, you need to rely on the `BudgetAttributes` type, which has the following input fields:

[source]
----
• title                 (optional) - JSON
• description           (optional) - JSON
• total_budget          (optional) - Integer
• weight                (optional) - Integer
----

== Sample request

The `UpdateBudget` mutation allows authenticated users to update budgets in a Decidim budget component. This mutation uses the existing `UpdateBudget` command from the admin controller.

[source,graphql]
----
mutation updateBudget($componentId: ID!, $budgetId: ID!, $input: UpdateBudgetInput!){
  component(id: $componentId){
    ...on BudgetsMutation{
      budget(id: $budgetId){
        update(input: $input){
          id
          url
        }
      }
    }
  }
}
----

Example of submitted variables

[source,json]
----
{
  "componentId": "3",
  "budgetId": "5",
  "input": {
    "attributes": {
      "totalBudget": 56700,
      "title": {
        "en": "Budget title changed from API"
      }
    }
  }
}
----

== Error Handling

The most frequent errors that can be generated by this mutation are as follows:

* xref:develop:api/reference/errors/unauthorized_mutation.adoc[Unauthorized Mutation Error - MUTATION_NOT_AUTHORIZED_ERROR]
* xref:develop:api/reference/errors/invalid_locale_error.adoc[Invalid Locale Error - INVALID_LOCALE_ERROR]
* xref:develop:api/reference/errors/attribute_validation_error.adoc[Attribute Validation Error - ATTRIBUTE_VALIDATION_ERROR]
* xref:develop:api/reference/errors/unauthorized_object.adoc[Unauthorized Object Error - UNAUTHORIZED_OBJECT_ERROR]

