= Update Result

== Input attributes

When you want to update a result in your accountability component, you need to rely on the `ResultAttributes` type, which has the following input fields:

[source]
----
• decidim_accountability_status_id  (Optional)   - Integer
• description                       (Optional)   - JSON
• end_date                          (Optional)   - String
• external_id                       (Optional)   - String
• parent_id                         (Optional)   - Integer
• progress                          (Optional)   - Float
• project_ids                       (Optional)   - Array
• proposal_ids                      (Optional)   - Array
• start_date                        (Optional)   - String
• taxonomies                        (Optional)   - Array
• title                             (Optional)   - JSON
• weight                            (Optional)   - Integer
----

== Sample request

The `UpdateResult` mutation allows authenticated users to update results in a Decidim accountability component. This mutation uses the existing `UpdateResult` command from the admin controller.

[source,graphql]
----
mutation updateResult($componentId: ID!, $resultId: ID!, $input: UpdateResultInput!){
  component(id: $componentId){
    ... on AccountabilityMutation {
      result(id: $resultId){
        update(input: $input){
          id
          url
        }
      }
    }
  }
}
----

Example of submitted variables

[source,json]
----
{
  "componentId": "1",
  "resultId": "18",
  "input": {
    "attributes": {
      "title": {
        "en": "My Result Title - updated"
      }
    }
  }
}
----

== Error Handling

The most frequent errors that can be generated by this mutation are as follows:

* xref:develop:api/reference/errors/unauthorized_mutation.adoc[Unauthorized Mutation Error - MUTATION_NOT_AUTHORIZED_ERROR]
* xref:develop:api/reference/errors/invalid_locale_error.adoc[Invalid Locale Error - INVALID_LOCALE_ERROR]
* xref:develop:api/reference/errors/attribute_validation_error.adoc[Attribute Validation Error - ATTRIBUTE_VALIDATION_ERROR]
* xref:develop:api/reference/errors/unauthorized_object.adoc[Unauthorized Object Error - UNAUTHORIZED_OBJECT_ERROR]

