= Updating Decidim

Because Decidim is a gem in our system, to update it we will have to edit our `Gemfile` and specify the new version number.

To keep our system up to date, we can visit the page https://github.com/decidim/decidim/releases[Releases] and compare with our `Gemfile`. See if the lines specifying the gem called "decidim-something" are followed by the number corresponding to the latest release:

[source,ruby]
----
gem "decidim", "0.29.0"
gem "decidim-conferences", "0.29.0"
gem "decidim-initiatives", "0.29.0"

gem "decidim-dev", "0.29.0"
----

To update, we recommend using small increments. From time to time we change the Ruby version or update dependencies, and skipping multiple versions at once can introduce breaking changes. Therefore, if you need to upgrade from v0.29.0 to v0.31.0, we recommend to first upgrade to v0.30.0, follow the release notes, and then, from v0.30.0 to upgrade to v0.31.0.

So, to perform the upgrade, we first follow the https://github.com/decidim/decidim/releases/tag/v0.30.0[release notes for v0.30.0], then, after we confirmed everything went OK, we should follow the https://github.com/decidim/decidim/releases/tag/v0.31.0[release notes for v0.31.0].

In theory, that would be all. However, you need to be careful in certain situations, specially if your copy of Decidim has many code modifications. We'd recommend to always test the upgrade following Ruby on Rails best practices: working with development mode in localhost, deploying to a staging/preproduction server to test it manually (specially your modifications) and finally deploying to production. As an alternative you can test the upgrade in a separate machine with the same configuration (If using DigitalOcean you can create an snapshot of the server, tested the update, and then remove it, similar process on other providers).

== From git repositories

For managing the gems we use the standard Rails gem called Bundler, where you can also point to https://bundler.io/v2.2/guides/git.html[git repositories and branches]. This is specially useful if you want to try an unreleased version, then you can do so by pointing to the release branch.

[source,ruby]
----
gem "decidim", git: "https://github.com/decidim/decidim", branch: "release/0.22-stable"
gem "decidim-conferences", git: "https://github.com/decidim/decidim", branch: "release/0.22-stable"
gem "decidim-initiatives", git: "https://github.com/decidim/decidim", branch: "release/0.22-stable"

gem "decidim-dev", git: "https://github.com/decidim/decidim", branch: "release/0.22-stable"
----

== DRY

You can also work with variables in your Gemfile so you can keep it DRY (Do not Repeat Yourself):

[source,ruby]
----
DECIDIM_VERSION = "0.21"

gem "decidim", DECIDIM_VERSION
gem "decidim-conferences", DECIDIM_VERSION
gem "decidim-initiatives", DECIDIM_VERSION

gem "decidim-dev", DECIDIM_VERSION
----

or

[source,console]
----
DECIDIM_VERSION = { git: 'https://github.com/decidim/decidim.git', branch: 'release/0.22-stable' }

gem "decidim", DECIDIM_VERSION
gem "decidim-conferences", DECIDIM_VERSION
gem "decidim-initiatives", DECIDIM_VERSION

gem "decidim-dev", DECIDIM_VERSION
----

== Compatibility versions matrix

There are different versions of Decidim that are compatible with different versions of Ruby and Node. You can check the following table to see which versions are compatible with each other:

include::install:partial$version_matrix.adoc[]

[discrete]
== Recommendations

. Make a full backup of the database before updating, just in case something unexpected happens.
. Never add 2 or more versions of Decidim to the same deployment to production, as the database structure could change, deprecated functions could be removed, causing issues that may prevent you to successfully run post release commands.
. If you are more than update away. Always update from one version to the immediately next one and then repeat the process until you are up to date.
. Always check the instructions for a certain version upgrade in https://github.com/decidim/decidim/releases[Releases]. Some releases require to perform certain actions as they may change some database structures. Follow that instructions if you are affected.
. Check also the file https://github.com/decidim/decidim/blob/develop/CHANGELOG.md[CHANGELOG] It may have relevant information for updates between versions.
