= Vote / Unvote Proposal

== Vote Proposal

To use the API to vote any proposal that is configured to receive votes, you will need to use the following API request.

[source,graphql]
----
mutation voteProposal($componentId: ID!, $proposalId: ID!){
  component(id: $componentId) {
    ... on ProposalsMutation {
      proposal(id: $proposalId) {
        vote(input: {}) {
        }
      }
    }
  }
}
----

Example of submitted variables

[source,json]
----
{
  "componentId": "9",
  "proposalId": "2"
}
----

=== Error Handling

The most frequent errors that can be generated by this mutation are as follows:

* xref:develop:api/reference/errors/unauthorized_mutation.adoc[Unauthorized Mutation Error - MUTATION_NOT_AUTHORIZED_ERROR]
* xref:develop:api/reference/errors/validation_error.adoc[Validation Error - VALIDATION_ERROR]
* xref:develop:api/reference/errors/unauthorized_object.adoc[Unauthorized Object Error - UNAUTHORIZED_OBJECT_ERROR]

== Unvote Proposal

To use the API to remove a vote on any proposal that you have already voted, you will need to use the following API request.

[source,graphql]
----
mutation unvoteProposal($componentId: ID!, $proposalId: ID!){
  component(id: $componentId) {
    ... on ProposalsMutation {
      proposal(id: $proposalId) {
        unvote(input: {}) {
        }
      }
    }
  }
}
----

Example of submitted variables

[source,json]
----
{
  "componentId": "9",
  "proposalId": "2"
}
----

=== Error Handling

The most frequent errors that can be generated by this mutation are as follows:

* xref:develop:api/reference/errors/unauthorized_mutation.adoc[Unauthorized Mutation Error - MUTATION_NOT_AUTHORIZED_ERROR]
* xref:develop:api/reference/errors/validation_error.adoc[Validation Error - VALIDATION_ERROR]
* xref:develop:api/reference/errors/unauthorized_object.adoc[Unauthorized Object Error - UNAUTHORIZED_OBJECT_ERROR]
